### ISSUE TITLE
Meta: Improve auto-paging in 'addTable()'

### ISSUE THREAD

**Issue by gitbrent** [gitbrent/PptxGenJS#48]
`addTable()` Development Items:

- [x] New option to disable auto-paging
- [x] New option to allow a line weight variable so users can adjust paging more precisely
- [x] Allow use of different `x` and `y` values after the initial page

Pingback: This Issue encapsulates Issue #43 and Issue #47 .

**Comment by gitbrent** [comment]
The most recent checkins complete all the items listed.

Thanks to everyone for the suggestions.
